# SPDX-License-Identifier: MIT
version: '2'

includes:
  local: ./tasks/BuildTasks.yml
  docker: ./tasks/DockerTasks.yml
  globalVars: ./Taskvars.yml

tasks:
  deploy-secrets:
    desc: Deploy secrets
    cmds:
    - |
      kubectl --context={{.CONTEXT_2_DEPLOY}} config view --raw --minify=true --flatten=true | \
      sed 's#server:.*#server: https://kubernetes.default.svc#g' > config
    - |
      kubectl --context={{.CONTEXT_2_DEPLOY}} create secret generic kube-config --from-file=config --dry-run --output=yaml | \
      kubectl --context={{.CONTEXT_2_DEPLOY}} --namespace {{.NAMESPACE_2_DEPLOY}} apply -f -
    - rm config

  deploy-local:
    desc: Deploy namespace-provisioner
    cmds:
    - kubectl --context={{.CONTEXT_2_DEPLOY}} --namespace={{.NAMESPACE_2_DEPLOY}} delete --filename=deploy/namespace-provisioner-{{.CONTEXT_2_DEPLOY}}.yaml --ignore-not-found
    - kubectl --context={{.CONTEXT_2_DEPLOY}} --namespace={{.NAMESPACE_2_DEPLOY}} apply --filename=deploy/namespace-provisioner-{{.CONTEXT_2_DEPLOY}}.yaml
